/*
 * Decompiled with CFR 0.152.
 */
package com.yonyoucloud.upc.billrule.userdefine;

import java.util.HashMap;

public class UserdefineClassMapperDefineId {
    public static final HashMap<String, String> PRODUCT_ARCHIVE;
    public static final HashMap<String, String> PRODUCT_SPEC;
    public static final HashMap<String, String> PRODUCT_SKU;
    public static final HashMap<String, Object> PRODUCT_CUSTOMER;
    public static final HashMap<String, Object> PRODUCT_BRAND;
    public static final HashMap<String, Object> VENDOR;
    public static final HashMap<String, Object> PRODUCT_BATCH_NO;
    public static final HashMap<String, Object> AA_CUSTOMER_PRO;
    public static final HashMap<String, Object> AA_MERCHANT_CUSTOMER_PRO;
    public static final HashMap<String, Object> AA_ORG_CUSTOMER_PRO;

    static {
        PRODUCT_BATCH_NO = new HashMap();
        AA_CUSTOMER_PRO = new HashMap();
        AA_MERCHANT_CUSTOMER_PRO = new HashMap();
        AA_ORG_CUSTOMER_PRO = new HashMap();
        VENDOR = new HashMap();
        VENDOR.put("vendordefine01", "define1");
        VENDOR.put("vendordefine02", "define2");
        VENDOR.put("vendordefine03", "define3");
        VENDOR.put("vendordefine04", "define4");
        VENDOR.put("vendordefine05", "define5");
        VENDOR.put("vendordefine06", "define6");
        VENDOR.put("vendordefine07", "define7");
        VENDOR.put("vendordefine08", "define8");
        VENDOR.put("vendordefine09", "define9");
        VENDOR.put("vendordefine10", "define10");
        VENDOR.put("vendordefine11", "define11");
        VENDOR.put("vendordefine12", "define12");
        VENDOR.put("vendordefine13", "define13");
        VENDOR.put("vendordefine14", "define14");
        VENDOR.put("vendordefine15", "define15");
        VENDOR.put("vendordefine16", "define16");
        VENDOR.put("vendordefine17", "define17");
        VENDOR.put("vendordefine18", "define18");
        VENDOR.put("vendordefine19", "define19");
        VENDOR.put("vendordefine20", "define20");
        VENDOR.put("vendordefine21", "define21");
        VENDOR.put("vendordefine22", "define22");
        VENDOR.put("vendordefine23", "define23");
        VENDOR.put("vendordefine24", "define24");
        VENDOR.put("vendordefine25", "define25");
        VENDOR.put("vendordefine26", "define26");
        VENDOR.put("vendordefine27", "define27");
        VENDOR.put("vendordefine28", "define28");
        VENDOR.put("vendordefine29", "define29");
        VENDOR.put("vendordefine30", "define30");
        PRODUCT_BRAND = new HashMap();
        PRODUCT_BRAND.put("define301", "define1");
        PRODUCT_BRAND.put("define302", "define2");
        PRODUCT_BRAND.put("define303", "define3");
        PRODUCT_BRAND.put("define304", "define4");
        PRODUCT_BRAND.put("define305", "define5");
        PRODUCT_BRAND.put("define306", "define6");
        PRODUCT_BRAND.put("define307", "define7");
        PRODUCT_BRAND.put("define308", "define8");
        PRODUCT_BRAND.put("define309", "define9");
        PRODUCT_BRAND.put("define310", "define10");
        PRODUCT_BRAND.put("define311", "define11");
        PRODUCT_BRAND.put("define312", "define12");
        PRODUCT_BRAND.put("define313", "define13");
        PRODUCT_BRAND.put("define314", "define14");
        PRODUCT_BRAND.put("define315", "define15");
        PRODUCT_BRAND.put("define316", "define16");
        PRODUCT_BRAND.put("define317", "define17");
        PRODUCT_BRAND.put("define318", "define18");
        PRODUCT_BRAND.put("define319", "define19");
        PRODUCT_BRAND.put("define320", "define20");
        PRODUCT_BRAND.put("define321", "define21");
        PRODUCT_BRAND.put("define322", "define22");
        PRODUCT_BRAND.put("define323", "define23");
        PRODUCT_BRAND.put("define324", "define24");
        PRODUCT_BRAND.put("define325", "define25");
        PRODUCT_BRAND.put("define326", "define26");
        PRODUCT_BRAND.put("define327", "define27");
        PRODUCT_BRAND.put("define328", "define28");
        PRODUCT_BRAND.put("define329", "define29");
        PRODUCT_BRAND.put("define330", "define30");
        PRODUCT_CUSTOMER = new HashMap();
        PRODUCT_CUSTOMER.put("customerDefine1", "define1");
        PRODUCT_CUSTOMER.put("customerDefine2", "define2");
        PRODUCT_CUSTOMER.put("customerDefine3", "define3");
        PRODUCT_CUSTOMER.put("customerDefine4", "define4");
        PRODUCT_CUSTOMER.put("customerDefine5", "define5");
        PRODUCT_CUSTOMER.put("customerDefine6", "define6");
        PRODUCT_CUSTOMER.put("customerDefine7", "define7");
        PRODUCT_CUSTOMER.put("customerDefine8", "define8");
        PRODUCT_CUSTOMER.put("customerDefine9", "define9");
        PRODUCT_CUSTOMER.put("customerDefine10", "define10");
        PRODUCT_CUSTOMER.put("customerDefine11", "define11");
        PRODUCT_CUSTOMER.put("customerDefine12", "define12");
        PRODUCT_CUSTOMER.put("customerDefine13", "define13");
        PRODUCT_CUSTOMER.put("customerDefine14", "define14");
        PRODUCT_CUSTOMER.put("customerDefine15", "define15");
        PRODUCT_CUSTOMER.put("customerDefine16", "define16");
        PRODUCT_CUSTOMER.put("customerDefine17", "define17");
        PRODUCT_CUSTOMER.put("customerDefine18", "define18");
        PRODUCT_CUSTOMER.put("customerDefine19", "define19");
        PRODUCT_CUSTOMER.put("customerDefine20", "define20");
        PRODUCT_CUSTOMER.put("customerDefine21", "define21");
        PRODUCT_CUSTOMER.put("customerDefine22", "define22");
        PRODUCT_CUSTOMER.put("customerDefine23", "define23");
        PRODUCT_CUSTOMER.put("customerDefine24", "define24");
        PRODUCT_CUSTOMER.put("customerDefine25", "define25");
        PRODUCT_CUSTOMER.put("customerDefine26", "define26");
        PRODUCT_CUSTOMER.put("customerDefine27", "define27");
        PRODUCT_CUSTOMER.put("customerDefine28", "define28");
        PRODUCT_CUSTOMER.put("customerDefine29", "define29");
        PRODUCT_CUSTOMER.put("customerDefine30", "define30");
        PRODUCT_ARCHIVE = new HashMap();
        PRODUCT_ARCHIVE.put("define91", "define1");
        PRODUCT_ARCHIVE.put("define92", "define2");
        PRODUCT_ARCHIVE.put("define93", "define3");
        PRODUCT_ARCHIVE.put("define94", "define4");
        PRODUCT_ARCHIVE.put("define95", "define5");
        PRODUCT_ARCHIVE.put("define96", "define6");
        PRODUCT_ARCHIVE.put("define97", "define7");
        PRODUCT_ARCHIVE.put("define98", "define8");
        PRODUCT_ARCHIVE.put("define99", "define9");
        PRODUCT_ARCHIVE.put("define100", "define10");
        PRODUCT_ARCHIVE.put("define101", "define11");
        PRODUCT_ARCHIVE.put("define102", "define12");
        PRODUCT_ARCHIVE.put("define103", "define13");
        PRODUCT_ARCHIVE.put("define104", "define14");
        PRODUCT_ARCHIVE.put("define105", "define15");
        PRODUCT_ARCHIVE.put("define106", "define16");
        PRODUCT_ARCHIVE.put("define107", "define17");
        PRODUCT_ARCHIVE.put("define108", "define18");
        PRODUCT_ARCHIVE.put("define109", "define19");
        PRODUCT_ARCHIVE.put("define110", "define20");
        PRODUCT_ARCHIVE.put("define111", "define21");
        PRODUCT_ARCHIVE.put("define112", "define22");
        PRODUCT_ARCHIVE.put("define113", "define23");
        PRODUCT_ARCHIVE.put("define114", "define24");
        PRODUCT_ARCHIVE.put("define115", "define25");
        PRODUCT_ARCHIVE.put("define116", "define26");
        PRODUCT_ARCHIVE.put("define117", "define27");
        PRODUCT_ARCHIVE.put("define118", "define28");
        PRODUCT_ARCHIVE.put("define119", "define29");
        PRODUCT_ARCHIVE.put("define120", "define30");
        PRODUCT_SKU = new HashMap();
        PRODUCT_SKU.put("define121", "define1");
        PRODUCT_SKU.put("define122", "define2");
        PRODUCT_SKU.put("define123", "define3");
        PRODUCT_SKU.put("define124", "define4");
        PRODUCT_SKU.put("define125", "define5");
        PRODUCT_SKU.put("define126", "define6");
        PRODUCT_SKU.put("define127", "define7");
        PRODUCT_SKU.put("define128", "define8");
        PRODUCT_SKU.put("define129", "define9");
        PRODUCT_SKU.put("define130", "define10");
        PRODUCT_SKU.put("define131", "define11");
        PRODUCT_SKU.put("define132", "define12");
        PRODUCT_SKU.put("define133", "define13");
        PRODUCT_SKU.put("define134", "define14");
        PRODUCT_SKU.put("define135", "define15");
        PRODUCT_SKU.put("define136", "define16");
        PRODUCT_SKU.put("define137", "define17");
        PRODUCT_SKU.put("define138", "define18");
        PRODUCT_SKU.put("define139", "define19");
        PRODUCT_SKU.put("define140", "define20");
        PRODUCT_SKU.put("define141", "define21");
        PRODUCT_SKU.put("define142", "define22");
        PRODUCT_SKU.put("define143", "define23");
        PRODUCT_SKU.put("define144", "define24");
        PRODUCT_SKU.put("define145", "define25");
        PRODUCT_SKU.put("define146", "define26");
        PRODUCT_SKU.put("define147", "define27");
        PRODUCT_SKU.put("define148", "define28");
        PRODUCT_SKU.put("define149", "define29");
        PRODUCT_SKU.put("define150", "define30");
        PRODUCT_SKU.put("define181", "define31");
        PRODUCT_SKU.put("define182", "define32");
        PRODUCT_SKU.put("define183", "define33");
        PRODUCT_SKU.put("define184", "define34");
        PRODUCT_SKU.put("define185", "define35");
        PRODUCT_SKU.put("define186", "define36");
        PRODUCT_SKU.put("define187", "define37");
        PRODUCT_SKU.put("define188", "define38");
        PRODUCT_SKU.put("define189", "define39");
        PRODUCT_SKU.put("define190", "define40");
        PRODUCT_SKU.put("define191", "define41");
        PRODUCT_SKU.put("define192", "define42");
        PRODUCT_SKU.put("define193", "define43");
        PRODUCT_SKU.put("define194", "define44");
        PRODUCT_SKU.put("define195", "define45");
        PRODUCT_SKU.put("define196", "define46");
        PRODUCT_SKU.put("define197", "define47");
        PRODUCT_SKU.put("define198", "define48");
        PRODUCT_SKU.put("define199", "define49");
        PRODUCT_SKU.put("define200", "define50");
        PRODUCT_SKU.put("define201", "define51");
        PRODUCT_SKU.put("define202", "define52");
        PRODUCT_SKU.put("define203", "define53");
        PRODUCT_SKU.put("define204", "define54");
        PRODUCT_SKU.put("define205", "define55");
        PRODUCT_SKU.put("define206", "define56");
        PRODUCT_SKU.put("define207", "define57");
        PRODUCT_SKU.put("define208", "define58");
        PRODUCT_SKU.put("define209", "define59");
        PRODUCT_SKU.put("define210", "define60");
        PRODUCT_SPEC = new HashMap();
        PRODUCT_SPEC.put("free1", "free1");
        PRODUCT_SPEC.put("free2", "free2");
        PRODUCT_SPEC.put("free3", "free3");
        PRODUCT_SPEC.put("free4", "free4");
        PRODUCT_SPEC.put("free5", "free5");
        PRODUCT_SPEC.put("free6", "free6");
        PRODUCT_SPEC.put("free7", "free7");
        PRODUCT_SPEC.put("free8", "free8");
        PRODUCT_SPEC.put("free9", "free9");
        PRODUCT_SPEC.put("free10", "free10");
    }
}

