@echo off
setlocal enabledelayedexpansion
title NCC YonBip Dev Skill - Uninstall

chcp 65001 >nul 2>&1

echo ============================================
echo   NCC YonBip Dev Skill Toolkit - Uninstall
echo ============================================
echo.

set "SKILLS_DIR=%USERPROFILE%\.claude\skills"
set "SETTINGS_FILE=%USERPROFILE%\.claude\settings.json"
set "LLM_WIKI_PATH_FILE=%USERPROFILE%\.llm-wiki-path"
set "REPO_DIR=%~dp0"

:: === 1. Remove skill junctions ===
echo [1/6] Removing installed skills...

set COUNT=0
for %%S in (yon-ncc-dev yonyou-bip-dev baoyu-url-to-markdown llm-wiki) do (
    set "SKILL_PATH=%SKILLS_DIR%\%%S"
    if exist "!SKILL_PATH!" (
        rmdir "!SKILL_PATH!" >nul 2>&1
        if exist "!SKILL_PATH!" (
            :: Still exists, might be a real directory (not junction)
            echo   %%S: [WARN] not a junction, use 'rmdir /s' manually if needed: !SKILL_PATH!
        ) else (
            echo   %%S: removed
            set /a COUNT+=1
        )
    ) else (
        echo   %%S: not installed, skipped
    )
)
echo   %COUNT% skill(s) removed.

:: === 2. Clean up settings.json ===
echo.
echo [2/6] Cleaning Claude Code permissions...

set "SKILLS_DIR_FWD=%SKILLS_DIR:\=/%"

python -c "
import json, os
settings_file = os.environ['SETTINGS_FILE']
skills_dir = os.environ['SKILLS_DIR']

if not os.path.exists(settings_file):
    print('   settings.json not found, skipped')
    exit(0)

with open(settings_file, 'r', encoding='utf-8') as f:
    cfg = json.load(f)

changed = False

# Remove skills directory from additionalDirectories
if 'permissions' in cfg and 'additionalDirectories' in cfg['permissions']:
    dirs = cfg['permissions']['additionalDirectories']
    if skills_dir in dirs:
        dirs.remove(skills_dir)
        changed = True
        print(f'   Removed skills directory from additionalDirectories')
    # Clean up empty list
    if not dirs:
        del cfg['permissions']['additionalDirectories']

# Clean up empty permissions container
if 'permissions' in cfg:
    if 'allow' in cfg['permissions'] and not cfg['permissions']['allow']:
        del cfg['permissions']['allow']
    if not cfg['permissions']:
        del cfg['permissions']

if changed:
    with open(settings_file, 'w', encoding='utf-8') as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
    print('   Done.')
else:
    print('   No changes needed.')
" 2>&1

if %errorlevel% neq 0 (
    echo   [WARN] Python script failed. Manually check: %SETTINGS_FILE%
)

:: === 3. Remove llm-wiki path file ===
echo.
echo [3/6] Removing llm-wiki knowledge base config...

if exist "%LLM_WIKI_PATH_FILE%" (
    del "%LLM_WIKI_PATH_FILE%"
    echo   Removed: %LLM_WIKI_PATH_FILE%
) else (
    echo   Not found, skipped.
)

:: === 4. Clean generated files inside repo ===
echo.
echo [4/6] Cleaning generated files inside repository...

set GEN_COUNT=0

:: 4a. npm node_modules
set "NODE_MODULES=%REPO_DIR%baoyu-url-to-markdown\scripts\node_modules"
if exist "!NODE_MODULES!" (
    rmdir /s /q "!NODE_MODULES!"
    echo   node_modules: removed
    set /a GEN_COUNT+=1
) else (
    echo   node_modules: not found, skipped
)

:: 4b. NCC class index files (generated by build_index.py, can be 50-75MB each)
for %%F in ("%REPO_DIR%yon-ncc-dev\class_index_*.json") do (
    if exist %%F (
        del "%%F"
        echo   %%~nxF: removed
        set /a GEN_COUNT+=1
    )
)

:: 4c. ncc_home_path.json (generated by build_index.py)
set "NCC_HOME=%REPO_DIR%yon-ncc-dev\ncc_home_path.json"
if exist "!NCC_HOME!" (
    del "!NCC_HOME!"
    echo   ncc_home_path.json: removed
    set /a GEN_COUNT+=1
)

:: 4d. decompiled source files
set "DECOMPILED=%REPO_DIR%decompiled"
if exist "!DECOMPILED!" (
    rmdir /s /q "!DECOMPILED!"
    echo   decompiled/: removed
    set /a GEN_COUNT+=1
)

:: 4e. yonyou-bip-dev decompiled
set "DECOMPILED_BIP=%REPO_DIR%yonyou-bip-dev\decompiled"
if exist "!DECOMPILED_BIP!" (
    rmdir /s /q "!DECOMPILED_BIP!"
    echo   yonyou-bip-dev/decompiled/: removed
    set /a GEN_COUNT+=1
)

if !GEN_COUNT! equ 0 (
    echo   No generated files found.
) else (
    echo   !GEN_COUNT! generated item(s) cleaned.
)

:: === 5. User config files ===
echo.
echo [5/6] User config files (db_config.json, bip_home_path.json)...

set CONFIG_COUNT=0
for %%F in (
    "%REPO_DIR%yonyou-bip-dev\db_config.json"
    "%REPO_DIR%yonyou-bip-dev\bip_home_path.json"
    "%REPO_DIR%yonyou-bip-dev\path_config.json"
) do (
    if exist %%F (
        echo   Found: %%~nxF (contains your credentials/paths)
        set /a CONFIG_COUNT+=1
    )
)

if !CONFIG_COUNT! gtr 0 (
    echo.
    set /p DEL_CONFIG="Delete these config files too? (contains your credentials) [y/N]: "
    if /i "!DEL_CONFIG!"=="y" (
        for %%F in (
            "%REPO_DIR%yonyou-bip-dev\db_config.json"
            "%REPO_DIR%yonyou-bip-dev\bip_home_path.json"
            "%REPO_DIR%yonyou-bip-dev\path_config.json"
        ) do (
            if exist %%F ( del "%%F" & echo   %%~nxF: deleted )
        )
    ) else (
        echo   Kept.
    )
) else (
    echo   None found, skipped.
)

:: === 6. Remove repo ===
echo.
echo [6/6] Repository cleanup...

set /p CONFIRM="Remove the entire repository at '%REPO_DIR%'? [y/N]: "
if /i "!CONFIRM!"=="y" (
    echo   Removing repository...
    cd /d "%USERPROFILE%"
    rmdir /s /q "%REPO_DIR%"
    if exist "%REPO_DIR%" (
        echo   [WARN] Could not fully remove. Close any programs using it and try manually.
    ) else (
        echo   Repository removed.
    )
) else (
    echo   Skipped. Repository kept at: %REPO_DIR%
)

:: === Done ===
echo.
echo ============================================
echo   Uninstall complete!
echo ============================================
echo.
echo   Cleaned up:
echo   [1] Skill junctions from %SKILLS_DIR%
echo   [2] settings.json permissions
echo   [3] llm-wiki config
echo   [4] Generated files (node_modules, class_index, decompiled, etc.)
echo   [5] User config files
echo   [6] Repository
echo ============================================

pause
