/*
 * Decompiled with CFR 0.152.
 */
package com.yonyoucloud.iuap.upc.constants;

import java.util.HashMap;
import java.util.HashSet;

public class ProductSaveFieldMap {
    public static HashSet<String> productFieldType = new HashSet(32);
    public static HashMap<String, String> productFieldRenameMap = new HashMap(256);
    public static HashMap<String, String> productApplyFieldRenameMap = new HashMap(16);
    public static final String API_PACKAGE = "com.yonyoucloud.iuap.upc.vo";
    public static final String PRODUCT_API_VO = "com.yonyoucloud.iuap.upc.vo.ProductApiVO";
    public static final String PRODUCT_DETAIL_VO = "com.yonyoucloud.iuap.upc.vo.ProductDetailVO";
    public static final String PRODUCT_ORG = "com.yonyoucloud.iuap.upc.vo.ProductOrgVo";
    public static final String MULTILINGUAL_VO = "com.yonyoucloud.iuap.upc.vo.MultilingualVO";
    public static final String PRODUCT_ASSIST_UNIT_EXCHANGES_VO = "com.yonyoucloud.iuap.upc.vo.ProductAssistUnitExchangesVO";
    public static final String PRODUCT_BAR_CODE = "com.yonyoucloud.iuap.upc.vo.ProductBarCodeVO";
    public static final String PRODUCT_DESCRIPTION_VO = "com.yonyoucloud.iuap.upc.vo.ProductDescriptionVO";
    public static final String PRODUCT_ATTACHMENT_VO = "com.yonyoucloud.iuap.upc.vo.ProductAttachmentVO";
    public static final String PRODUCT_ALBUM_VO = "com.yonyoucloud.iuap.upc.vo.ProductAlbumVO";
    public static final String PRODUCT_ASSIST_CLASS_VO = "com.yonyoucloud.iuap.upc.vo.ProductAssistClassVO";
    public static final String PRODUCT_TAGS = "com.yonyoucloud.iuap.upc.vo.ProductTag";
    public static final String PRODUCT_APPLY = "com.yonyoucloud.iuap.upc.vo.ProductApplyVO";
    public static final String PRODUCT_LOAD_WAY = "com.yonyoucloud.iuap.upc.vo.ProductLoadWayVO";

    static {
        productFieldType.add(PRODUCT_DETAIL_VO);
        productFieldType.add(PRODUCT_ORG);
        productFieldType.add(MULTILINGUAL_VO);
        productFieldType.add(PRODUCT_ASSIST_UNIT_EXCHANGES_VO);
        productFieldType.add(PRODUCT_BAR_CODE);
        productFieldType.add(PRODUCT_DESCRIPTION_VO);
        productFieldType.add(PRODUCT_ATTACHMENT_VO);
        productFieldType.add(PRODUCT_ALBUM_VO);
        productFieldType.add(PRODUCT_ASSIST_CLASS_VO);
        productFieldType.add(PRODUCT_TAGS);
        productFieldType.add(PRODUCT_LOAD_WAY);
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productOrges", "productOrgs");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productAssistUnitExchanges", "productAssistUnitExchanges");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productBarCodes", "productBarCodes");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.description", "description");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.detail", "detail");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.storeOffAndOffState", "iStatus");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.orderLoadAndUnloadStatus", "iUOrderStatus");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.purchaseRate", "purchaserate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.stockRate", "stockrate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.batchRate", "batchrate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.onlineRate", "onlinerate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.offlineRate", "offlinerate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.requireRate", "requirerate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.batchPriceRate", "batchpricerate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.markPrice", "fMarkPrice");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.salePrice", "fSalePrice");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.marketPrice", "fMarketPrice");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.primeCosts", "fPrimeCosts");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.settleAccountsRate", "fSettleAccountsRate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.batchManage", "isBatchManage");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.expiryDateManage", "isExpiryDateManage");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.serialNoManage", "isSerialNoManage");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.minOrderQuantity", "iMinOrderQuantity");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.orderDlyFeeRuleId", "uorderDlyFeeRuleId");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.enableCyclePurchase", "iEnableCyclePurchase");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.enableModifyDeposit", "enablemodifyDeposit");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.inventoryCount", "lInventoryCount");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.templateOfFreightId", "dlyFeeRuleId");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.baseSaleCount", "iBaseSaleCount");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.allArea", "isAllArea");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.enableContractManagement", "iEnableEcontract");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.priceChangeAllowed", "isPriceChangeAllowed");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.saleInOfflineStore", "isSaleInOfflineStore");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.offlineStoreOrder", "isOfflineStoreOrder");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.offlineStoreReturn", "isOfflineStoreReturn");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.weighingOrNot", "isWeight");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.process", "isProcess");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.material", "isMaterial");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.noTaxCostPrice", "fNoTaxCostPrice");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.orderUpTime", "uorderUpTime");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.mallUpCount", "mallupcount");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.mallDownCount", "malldowncount");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.orderUpCount", "uorderupcount");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.orderDownCount", "uorderdowncount");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.timestamp", "pubts");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.stopStatus", "stopstatus");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.stopTime", "stoptime");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.checkFree", "isCheckFree");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.order", "iOrder");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.recommend", "isRecommend");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.planOrderLimit", "fplanorderlimit");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.incomeTaxRates", "inTaxrate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.incomeTaxRatesCode", "inTaxrate_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.incomeTaxRatesName", "inTaxrate_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.outputTaxRate", "outTaxrate");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.outTaxRateCode", "outTaxrate_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.outTaxRateName", "outTaxrate_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.barcodeManage", "isBarcodeManage");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.registrationManager", "isregistrationmanager");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.authorizationManager", "isauthorizationmanager");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.sunshinePurchase", "sunshinePurchaseNo");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.registrationNumber", "registrationNo");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.doubleSale", "iDoubleSale");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.expiryDateCalculationMethod", "isExpiryDateCalculationMethod");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.lowestMarkPrice", "fLowestMarkPrice");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.displayPrice", "isDisplayPrice");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.purchaseUnitCode", "purchaseUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.purchaseUnitName", "purchaseUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.purchasePriceUnitCode", "purchasePriceUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.purchasePriceUnitName", "purchasePriceUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.stockUnitCode", "stockUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.stockUnitName", "stockUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.produceUnitCode", "produceUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.produceUnitName", "produceUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.batchPriceUnitCode", "batchPriceUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.batchPriceUnitName", "batchPriceUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.batchUnitCode", "batchUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.batchUnitName", "batchUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.onlineUnitCode", "onlineUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.onlineUnitName", "onlineUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.offlineUnitCode", "offlineUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.offlineUnitName", "offlineUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.requireUnitCode", "requireUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.requireUnitName", "requireUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.demandPlanningUnitCode", "demandPlanningUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.demandPlanningUnitName", "demandPlanningUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductOrgVo.orgCode", "orgId_code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.inspectionUnitCode", "inspectionUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.inspectionUnitName", "inspectionUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductAssistUnitExchangesVO.assistUnitCode", "assistUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductAssistUnitExchangesVO.assistUnitName", "assistUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductAssistUnitExchangesVO.mainUnitCount", "mainUnitCountNew");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productCharacterDef", "productCharacterDef");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.productExtendCharacterDef", "productExtendCharacterDef");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.autoGenerateRangeData", "autoGenerateRangeData_");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.manageClassCode", "manageClass_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.manageClassName", "manageClass_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productClassCode", "productClass_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.purchaseClassCode", "purchaseClass_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.purchaseClassName", "purchaseClass_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.unitCode", "unit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.unitName", "unit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.orgCode", "orgId_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productAttribute", "productattribute");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.mnemonicCode", "mnemoniccode");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.authorizationManager", "isAuthorizationManager");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.registrationManager", "isRegistrationManager");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.deleted", "isDeleted");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.transType", "transType");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.transTypeCode", "transType_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.transTypeName", "transType_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.optionalMaterial", "isOptionalMaterial");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.derivedMaterial", "isDerivedMaterial");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.optionalMaterialCode", "optionalMaterialId_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.optionalMaterialName", "optionalMaterial_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productTemplateName", "productTemplate_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productLineCode", "productLine_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.productLineName", "productLine_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.brandCode", "brand_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.brandName", "brand_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.weightUnitCode", "weightUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.weightUnitName", "weightUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.volumeUnitCode", "volumeUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.volumeUnitName", "volumeUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.netWeightUnitCode", "netWeightUnit_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.netWeightUnitName", "netWeightUnit_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.planClassCode", "planClass_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.planClassName", "planClass_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.taxClassCode", "taxClass_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.taxClassName", "taxClass_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.manufacturePlannerCode", "manufacturePlanner_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.manufacturePlannerName", "manufacturePlanner_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.produceDepartmentCode", "produceDepartment_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.produceDepartmentName", "produceDepartment_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.returnWarehouseCode", "returnWarehouse_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.returnWarehouseName", "returnWarehouse_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.deliveryWarehouseCode", "deliveryWarehouse_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.deliveryWarehouseName", "deliveryWarehouse_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.omsWarehouseCode", "deliveryWarehouse_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.omsWarehouseName", "deliveryWarehouse_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.receiptWarehouseCode", "receiptWarehouse_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.receiptWarehouseName", "receiptWarehouse_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.warehouseManagerCode", "warehouseManager_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.warehouseManagerName", "warehouseManager_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.productBuyerCode", "productBuyer_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.productBuyerName", "productBuyer_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.productVendorCode", "productVendor_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.productVendorName", "productVendor_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.stockABCClass", "iABCClass");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.costClassCode", "costClass_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.costClassName", "costClass_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductAssistUnitExchangesVO.status", "_status");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductAssistClassVO.productClassCode", "productClass_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductAssistClassVO.productClassName", "assClass_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductAssistClassVO.status", "_status");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.costItemsCode", "costItems_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.costItemsName", "costItems_Name");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.materialStatusId", "materialStatus");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApiVO.materialStatusCode", "materialStatus_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.materialStatusId", "materialStatus");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.materialStatusCode", "materialStatus_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.billingUnitId", "billingUnit");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.virtualPart", "virtualPart");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductDetailVO.productLoadWays", "productLoadWay");
        productApplyFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApplyVO.applyDepartmentCode", "applyDepartment_Code");
        productApplyFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApplyVO.applyDepartmentName", "applyDepartment_Name");
        productApplyFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApplyVO.bizOperatorCode", "bizOperator_Code");
        productApplyFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApplyVO.bizOperatorName", "bizOperator_Name");
        productApplyFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.ProductApplyVO.applyOrgCode", "applyOrg_Code");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.MultilingualVO.receiptSpecMultilingual", "receiptSpec");
        productFieldRenameMap.put("com.yonyoucloud.iuap.upc.vo.MultilingualVO.receiptModelMultilingual", "receiptModel");
    }
}

