/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  nc.vo.ml.NCLangRes4VoTransl
 */
package nc.vo.arap.global;

import nc.vo.ml.NCLangRes4VoTransl;

public class ArapBillDealVOConsts {
    public static final String FI = "fi";
    public static final int OBJTYPE_CUSTOMER = 0;
    public static final int OBJTYPE_SUPPLIER = 1;
    public static final int OBJTYPE_DEPT = 2;
    public static final int OBJTYPE_PSN = 3;
    public static String DEFAULTNULL = "~";
    public static final String SIMPCHN = "simpchn";
    public static final String ENGLISH = "english";
    public static Integer RBVERIFY_FLAG = 2;
    public static Integer SAMEVERIFY_FLAG = 0;
    public static Integer UNSAMEVERIFY_FLAG = -1;
    public static Integer DISCTIONVERIFY_FLAG = -2;
    public static Integer BACKONVERIFY_FLAG = -3;
    public static String BILL_CLASS_YS = "ys";
    public static String BILL_CLASS_SK = "sk";
    public static String BILL_CLASS_YF = "yf";
    public static String BILL_CLASS_FK = "fk";
    public static Integer DIRECTION_JF = 1;
    public static Integer DIRECTION_DF = -1;
    public static Integer INT_ZERO = 0;
    public static Integer INT_ONE = 1;
    public static Integer INT_TWO = 2;
    public static String DEFHEAD = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0600");
    public static String DEFBODY = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0601");
    public static String ONMANVERIFY_NODE = "20060MV";
    public static final String BILLTYPE_INFORMER = "36S3";
    public static final String BILLTYPE_36D1 = "36D1";
    public static final String BILLTYPE_36D7 = "36D7";
    public static final String BILLTYPE_21 = "21";
    public static final String BILLTYPE_25 = "25";
    public static final String BILLTYPE_30 = "30";
    public static final String BILLTYPE_32 = "32";
    public static final String BILLTYPE_Z2 = "Z2";
    public static final String BILLTYPE_Z3 = "Z3";
    public static final String BILLTYPE_45 = "45";
    public static final String BILLTYPE_4D46 = "4D46";
    public static final String BILLTYPE_4D48 = "4D48";
    public static final String BILLTYPE_4D50 = "4D50";
    public static Integer SYSCODE_AR = 0;
    public static Integer SYSCODE_AP = 1;
    public static Integer AGIOTAGE_FLAG = 1;
    public static Integer AGIOTAGE_YSX_FLAG = 12;
    public static Integer AGIOTAGE_WSX_FLAG = 14;
    public static Integer AGIOTAGE_WSXHC_FLAG = 13;
    public static String YSX_AGIOTAGE_COMMNET = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0419");
    public static String WSX_AGIOTAGE_COMMNET = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0420");
    public static String WSXHC_AGIOTAGE_COMMNET = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0421");
    public static String AGIOTAGE_COMMNET = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0418");
    public static final Integer BZ_OUT_5 = 5;
    public static final Integer BZ_IN_6 = 6;
    public static final String YS = "Ys";
    public static final String YF = "Yf";
    public static final String SK = "Sk";
    public static final String FK = "Fk";
    public static final String YSCOMMENT = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0602");
    public static final String YFCOMMENT = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0603");
    public static final String FKCOMMENT = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0604");
    public static final String SKCOMMENT = NCLangRes4VoTransl.getNCLangRes().getStrByID("2006pub_0", "02006pub-0605");
    public static final int YSFLAG = 0;
    public static final int SKFLAG = 1;
    public static final int YFFLAG = 2;
    public static final int FKFLAG = 3;
    public static final Integer HZFS_3 = 3;
    public static final Integer HZSH_4 = 4;
    public static String VERIFY_D9 = "D9";
    public static String VERIFY_D9AP = "D9AP";
    public static String AGIOTAGE_DU = "DU";
    public static String AGIOTAGE_DUAP = "DUAP";
    public static String DEBT_DA = "DA";
    public static String DEBT_DB = "DB";
    public static String DEBT_DAK = "DAK";
    public static String DEBT_DBK = "DBK";
    public static String BADDEBTS_LOSE = "DL";
    public static String BADDEBTS_BACK = "DK";
    public static String BADDEBTS_DSTL = "DSTL";
    public static final String TYPE_VERIFY_BEFORE = "20061070";
    public static final String TYPE_VERIFY_AFTER = "20061071";
    public static final String TYPE_UNVERIFY_BEFORE = "20061072";
    public static final String TYPE_UNVERIFY_AFTER = "20061073";
    public static final String TYPE_DEBT_BEFORE = "20061080";
    public static final String TYPE_DEBT_AFTER = "20061081";
    public static final String TYPE_UNDEBT_BEFORE = "20061082";
    public static final String TYPE_UNDEBT_AFTER = "20061083";
    public static final String TYPE_ESTVERIFY_BEFORE = "20061030";
    public static final String TYPE_ESTVERIFY_AFTER = "20061031";
    public static final String TYPE_UNESTVERIFY_BEFORE = "20061032";
    public static final String TYPE_UNESTVERIFY_AFTER = "20061033";
    public static final String TYPE_BADDEBTLOSE_BEFORE = "20061090";
    public static final String TYPE_BADDEBTLOSE_AFTER = "20061091";
    public static final String TYPE_BADDEBTBACK_BEFORE = "20061092";
    public static final String TYPE_BADDEBTBACK_AFTER = "20061093";
    public static final String TYPE_UNBADDEBTLOSE_BEFORE = "20061094";
    public static final String TYPE_UNBADDEBTLOSE_AFTER = "20061095";
    public static final String TYPE_UNBADDEBTBACK_BEFORE = "20061096";
    public static final String TYPE_UNBADDEBTBACK_AFTER = "20061097";
    public static final String TYPE_PAUSE_BEFORE = "20061040";
    public static final String TYPE_PAUSE_AFTER = "20061041";
    public static final String TYPE_PAUSECANCEL_BEFORE = "20061042";
    public static final String TYPE_PAUSECANCEL_AFTER = "20061043";
    public static final String ACTION_VERIFY = "verify";
    public static final String ACTION_DTLVERIFY = "dtlverify";
    public static final String ACTION_UNVERIFY = "unverify";
    public static final String ACTION_PARTUNVERIFY = "partUnVer";
    public static final String ACTION_SIMVERIFY = "sim";
    public static final String ACTION_LINKBILL = "linkbill";
    public static final String ACTION_DTLLINKBILL = "dtllinkbill";
    public static final String ACTION_VERIFYQUERY = "verquery";
    public static final String ACTION_WINDOH = "windoh";
    public static final String ACTION_WINDOV = "windov";
    public static final String ACTION_SELALL = "selall";
    public static final String ACTION_SELNONE = "selnone";
    public static final String ACTION_JFMATH = "Jfmath";
    public static final String ACTION_DFMATH = "dfmath";
    public static final String ACTION_CASELOAD = "caseload";
    public static final String ACTION_CASESAVE = "casesave";
}

